### PR TITLE
A couple of small fixes

### PR DESCRIPTION
**Pull request by edouarda**
- Fixes Boost 1.49.0 incompatibilities
- Fixes Clang incompatibilities
- Fixes broken reentrant code

### CODE REVIEW

**Comment by deanberris** [comment]
@edouarda -- so sorry for the delay here; it's been almost three years (!!!) and I hadn't actually been paying attention on the @mikhailberis account!

Can you send this pull request instead to deanberris/memcachepp so I can merge it properly? I don't use the @mikhailberis account anymore. :frowning:

**Comment by edouarda** [comment]
Hi, no problem, I will do it ASAP!

**Comment by mikhailberis** [comment]
Thanks Edouard!

**Comment by edouarda** [comment]
Sorry I think I did the pull to the wrong repo again. Fixed it.

**Pull request closed without merging**
